
// PBIDesignerConfig.json
GET https://go.microsoft.com/fwlink/?LinkID=524399

###

// Current version announcement (blog post)
GET https://go.microsoft.com/fwlink/?LinkID=524795

###

// Current version of PBID from Microsoft Download Center
GET https://www.microsoft.com/en-us/download/details.aspx?id=58494

###

// Direct download for previous versions, see: https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive
GET https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup-2020-04_x64.exe
